### ISSUE TITLE
Still Can't Place Items on the Grill

### ISSUE THREAD

**Issue by earthcrafterman** [kawaiiwolf/kawaiicrops#4]
Your fix did not work, so I'm reposting

I am really interested in using your mod, and in trying to make a grill recipe, I've found that I am unable to place any items on the grill. I've tried both right clicking on it and dropping items on it. I personally feel really nooby for not knowing this, and really need a little help as to what to do. I've found I can place a steamer on a pan, but no actual items in it. Adding a recipe to the grill does not work either as you can see here:

"kawaiicraft grill recipes" {
    #  [default: ]
    S:0=customItems:cooked_beef 1 customitems:raw_beef 10 12

    #  [default: ]
    S:1=customitems:cooked_mutton 1 customitems:raw_mutton 8 11

    #  [default: ]
    S:2=customitems:cooked_chicken 1 customitems:raw_chicken 4 6

    #  [default: ]
    S:3=customitems:cooked_pork 1 customitems:raw_pork 6 8
}

**Comment by kawaiiwolf** [comment]
Added tooltip to grill as a reminder that it needs to be HOT before using. NEI integration also demonstrates which blocks will do this as a reminder.
