### ISSUE TITLE
Quantity and/or Weight issue with "Nothing"

### ISSUE THREAD

**Issue by Xltimus** [kawaiiwolf/kawaiicrops#5]
Forge 10.13.2.1272 & Forge 10.13.2.1286
kawaiicrops 0.5.7b / kawaiicrops 0.5.8b

Using the configurations to give a fruit with a weight of 1 and a "nothing" with a weight results in a crash when initializing the game. The example: "nothing 1 99, minecraft:diamond 1 1", from the examples in general.cfg notably results in the same exact crash.

http://pastebin.com/fHu7LiK1

[EDIT] Still seems to be broken in 0.5.8b

**Comment by kawaiiwolf** [comment]
Yup ! This was a parsing derp, fixed in 0.5.9 !
