### ISSUE TITLE
[NEI] Utility search w/ oreDictionary recipes crash

### ISSUE THREAD

**Issue by Xltimus** [kawaiiwolf/kawaiicrops#8]
Forge 10.13.2.1286
kawaiicrops 0.5.8b
CodeChickenCore-1.7.10-1.0.4.35
NotEnoughItems-1.7.10-1.0.4.83

Probably best explained via example...
"minecraft:brown_mushroom", "minecraft:red_mushroom", and "harvestcraft:whitemushroomItem" are all members of the "listAllmushroom" oreDictionary group.

I am using "harvestcraft:grilledmushroomItem 1 listAllmushroom 1 1" as a recipe for the grill. 

• I am able to cook the items just fine.
• Looking up the recipe of a "harvestcraft:grilledmushroomItem" works, the various mushrooms cycle correctly.
• However, attempting to do a utility check (seeing what all can be crafted from an item) on any of the members of "listAllmushroom" will cause a "Updating screen events" crash.

http://pastebin.com/TQKS2Z1k

[EDIT] Actually it seems like having an oreDictionary entry as part of a recipe COMPLETELY breaks any and all utility searching, regardless of what item is being looked up.

**Comment by karmarcharger** [comment]
If you cant search, it means you messed up a recipe somewhere in the config, perhaps Oredict isnt supported, and hence isnt a valid code for your recipe?

**Comment by kawaiiwolf** [comment]
Ore dictionary works, or at least it did until forge broke it. It decided to stick ArrayLists into ArrayLists when I was just expecting ItemStacks >.> Anyway, it's all fixed for the next update assuming no more table cloth tugging of the internal mechanics !
