### ISSUE TITLE
Annoying Trees

### ISSUE THREAD

**Issue by earthcrafterman** [kawaiiwolf/kawaiicrops#9]
While working on my NAM modpack, I've found that trees did not have an option for not growing fruit, a feature I very much would have liked, as I feel that I'd rather add other types of trees apart from just fruit-bearing ones. Additionally, I've found that leaves are the same item as saplings. And that's very nice, but I'm afraid I'm unable to get the leaves by shearing, which is quite annoying considering my using of Enviromine. While I've found a couple of work-arounds for these, I decided it best to bring it to attention so that at the very least you'd know these are concerns, small as they may be.

**Comment by kawaiiwolf** [comment]
These are for fruit/item growing trees ! There are plenty of other mods out there that do generic trees but I didn't want to get into creating woods and all the craziness that goes into that. There's nothing to stop you from having a tree that grows sticks, leaves, acorns, cinnamon, etc. ? Use identical leaf textures for the "fruit" block and just set the growth/spawn multipliers nice and low !  Leave the drop tables empty if you want for "fruit". I did, however, add a drop table for when leaves are sheared. Look for it in the next update !  Note: A sheared leaf will drop from both it's sheared table and the appropriate destroyed table (Destroyed Leaf, Ripe Fruit or Unripe Fruit).
